### PR TITLE
feat: allow analysis elf before initialization vm

### PR DESCRIPTION
**Pull request by mohanson**
Add a new package level function `parse_elf()` and  a new method `DefaultMachine.load_program_elf(&mut self, program: &Bytes, args: &[Bytes], elf: &Elf,)`, this allows analysis of the elf file before initializing the vm, while ensuring that it only needs to be parsed once.

### CODE REVIEW

**Comment by xxuejie** [comment]
Can we put this on hold for now? I want to spend some time to think the best way to approach this feature.

**Comment by mohanson** [comment]
Okay, we should treat it cautiously.

**Review by xxuejie — APPROVED** [review]

**Comment by xxuejie** [comment]
The PR title needs updating @mohanson

**Comment by mohanson** [comment]
> The PR title needs updating @mohanson

Done.

**Pull request merged**
